---
title: "exercise1"
author: "Karim Semin"
date: "4/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
```

```{r}
ODE = read.table("data/ODI-2021_trimmed.csv",header=TRUE, sep = ',', fill=TRUE)[,c(3:18)]
ODE
```

```{r}
gender_vs_stress = data %>% select(5, 10)
boxplot(gender_vs_stress)
```


make a model, use stress, gender, 
```{r}
ODE$stress = ODE$What.is.your.stress.level..0.100..
ODE$gender = as.factor(ODE$What.is.your.gender.)

ODE2 = ODE %>% filter(gender != "unknown", gender != "")

ODE2$gendernum[ODE2$gender=="male"] <- 0; ODE2$gendernum[ODE2$gender=="female"] <- 1


ODE_glm = select(ODE2, gender, gendernum, stress, chocolate)
ODE_glm$chocolate
length(ODE_glm$gender[ODE_glm$chocolate == "fat" & ODE_glm$gender=="female"])

genderglm = glm(gendernum~stress, data = ODE_glm, family=binomial, na.action=na.omit)
```

Now we cross-validate
Typical k values: 5 and 10

1. Select 1/10 of the data and set it
aside for evaluation
2. Train the classifier on the rest (9/10) 1
3. Test on the selected /10
4. Remember the evaluation scores
5. Set aside another 1/10 for testing, and repeat the above
6. Altogether, there will be 10 rounds of training+testing
7. Take the average of the eval scores

0 = male
1 = female
```{r}
ODE$bedtime
ODE$chocolate

ODE_glm
length(ODE_glm$gender)
length(ODE_glm$choco)

plot(ODE_glm$stress[ODE_glm$gendernum == 1])
plot(ODE_glm$stress)

plot(ODE$Give.a.random.number[ODE$Give.a.random.number < 500])

set.seed(42)
random_order = ODE_glm[sample(nrow(ODE_glm)), ]
random_order

one_tenth = as.integer(length(ODE_glm$gender)/10)
one_tenth

for (b in 1:1) {
  evaluation = random_order[1:18,]
  random_order = tail(random_order, -18)
  test_set = ODE_glm[!row.names(ODE_glm) %in% row.names(evaluation[0]),]
  test_set
  
  exp_glm = glm(gendernum~stress, data = test_set, family=binomial, na.action=na.omit)
  
  person = evaluation[18,]
  person
  ans = predict(exp_glm, person)
  # predict(fruitflieslm2a, data.frame(thorax=mean_length, activity=c('high','low','isolated')))
}
ans
```






